### PR TITLE
Add consumer proguard rules

### PR DESCRIPTION
**Pull request by joshfriend**
I can't figure out how to build a jar for this project, but this setup is supposed to work and automatically provide the right proguard rules for anyone using R8 or proguard v6+ (bundled with AGP 3.2+)

### CODE REVIEW

**Comment by commonsguy** [comment]
> I can't figure out how to build a jar for this project

Run the `netsecurity:jarRelease` Gradle task.

> this setup is supposed to work and automatically provide the right proguard rules for anyone using R8 or proguard v6+ (bundled with AGP 3.2+)

AFAIK, a JAR does not contain ProGuard rules. `consumerProguardFiles` should work in AAR packaging.

I will look into incorporating `consumerProguardFiles` (whether via your PR or a separate implementation) when I next need to make changes to this library. Thanks for the suggestion!

**Comment by joshfriend** [comment]
If the jar includes proguard files in `META-INF/proguard`, R8 will use it (https://twitter.com/JakeWharton/status/1004401938467876865). Libraries like OkHttp, Moshi and Retrofit are currently distributing consumer proguard rules this way. I'll see if I can spend a bit more time on this to get it working, I didn't realize `consumerProguardFiles` only applies to AARs.

**Comment by joshfriend** [comment]
Jar files can contain proguard rules that R8 will use as long as they are in the `META-INF/proguard/` folder: https://developer.android.com/studio/build/shrink-code#configuration-files

**Comment by commonsguy** [comment]
Sorry, but I have elected to discontinue work on this library.

As I note in the revised `README`, for certificate pinning, consider just using [OkHttp](https://github.com/square/okhttp)
and its [built-in support for certificate pinning](https://square.github.io/okhttp/https/#certificate-pinning-kt-java). If you need certificate pinning elsewhere, consider [TrustKit-Android](https://github.com/datatheorem/TrustKit-Android).

**Pull request closed without merging**
